openapi: 3.0.0
info:
  title: Get Spotify Data
  version: 1.0.0

paths:
  /api/token:
    get:
      summary: Get Spotify Token
      operationId: getToken
      parameters:
        - $ref: "#/components/parameters/AuthSecret"
      responses:
        "200":
          description: A Spotify Bearer Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  parameters:
    AuthSecret:
      name: secret
      in: query
      required: true
      schema:
        type: string

  responses:
    Unauthorized:
      description: Unauthorized — secret is invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Token:
      type: object
      properties:
        access_token:
          type: string
          description: The access token to use for API calls.
        expiry:
          type: integer
          description: The time in seconds until the token expires.
      required:
        - access_token
        - expiry

    Error:
      type: object
      properties:
        error:
          type: string
        display_message:
          type: string
      required:
        - error
      optional:
        - display_message
